apiVersion: v1
kind: Pod
metadata:
  name: alain-nginx
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80
    livenessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 20
    readinessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 10
      periodSeconds: 15
    env:
    - name: DB_CONNECT
      valueFrom:
        configMapKeyRef:
          name: alaindev-env
          key: DB_URL